/* @include "src/ui/menus/install.js" */
/* @include "src/ui/menus/context.js" */
/* @include "src/ui/menus/title.js" */
/* @include "src/ui/menus/play.js" */
/* @include "src/ui/menus/free-play.js" */
/* @include "src/ui/menus/achievements.js" */
/* @include "src/ui/menus/museum.js" */
/* @include "src/ui/menus/options.js" */
/* @include "src/ui/menus/integration.js" */
