// Seven optional-to-practise, mandatory-in-campaign final encounters. Existing 56 sectors are unchanged.
const BOSS_BOOK=[
 {name:'QA-RL · COMPACTADOR',short:'QA-RL',color:'#8af9df',warning:'¡APÁRTATE DE LAS PRENSAS!',intro:'He actualizado el protocolo. Ahora incluye una prensa de seis toneladas.',open:'La prensa se ha atascado. ¡Salta al núcleo verde!',outro:'QA-RL: «El defecto acaba de mejorar mis especificaciones. Qué incómodo».',lore:'El módulo de recuperación registra que 0G-17 aprende de cada intento. Dr. Chew bloquea su orden de destrucción.'},
 {name:'BARÓN BURBUJA XL',short:'BARÓN BURBUJA',color:'#ffce85',warning:'¡ESQUIVA LA ESPUMA!',intro:'La etiqueta decía «no agitar». Alguien lo interpretó como un reto.',open:'¡Sin presión! Golpea la válvula verde.',outro:'Dr. Chew: «Bueno. Ya sabemos por qué no se debe agitar».',lore:'La sobrepresión abre una vía hasta Candy City. En el registro aparece una orden: recuperar el lote vivo.'},
 {name:'BUBBLE · EGO TURBO',short:'BUBBLE',color:'#eea4ff',warning:'¡SALTA SU EMBESTIDA!',intro:'Mis abogados dicen que no puedo perder contra alguien con patitas.',open:'¡Mareado! Salta al emblema verde.',outro:'Bubble: «Era una exhibición. Ganar habría sido vulgar».',lore:'Bubble es del lote 0G-16. También puede decidir. Fingía perseguir a Gum para enseñarle la ruta de escape.'},
 {name:'CRYO-FAN 9000',short:'CRYO-FAN',color:'#acf0ff',warning:'BAJO: SALTA · ALTO: QUÉDATE ABAJO',intro:'Temperatura recomendada para las ideas propias: menos cuarenta.',open:'Se recalienta. ¡Al núcleo verde!',outro:'QA-RL: «No es una derrota. Es una descongelación no programada».',lore:'El polímero no solo conserva el sabor: conserva recuerdos. QA-RL reconoce sus anteriores encuentros con Gum.'},
 {name:'LA TEMPLADORA MAYOR',short:'TEMPLADORA',color:'#ffc38d',warning:'¡CUIDADO CON LA LLUVIA DE CACAO!',intro:'El chocolate tiene un punto de templado. Tú estás a punto de perder el tuyo.',open:'¡El cucharón está vacío! Salta al núcleo.',outro:'Dr. Chew: «La cobertura no cuenta como equipo de protección».',lore:'Dr. Chew admite que el proyecto buscaba un producto que se adaptara al consumidor. Gum ha aprendido a negarse.'},
 {name:'PACK-O-MATIC SUPREME',short:'PACK-O-MATIC',color:'#d0b5ff',warning:'ESQUIVA CAJAS · SALTO / CHICLE: ABRE',intro:'Su libertad será enviada en una caja de tamaño insuficiente.',open:'¡Sin papel! Al botón verde de emergencia.',outro:'QA-RL: «Quizá el problema no era el producto. Quizá eran las cajas».',lore:'QA-RL cambia su objetivo: proteger al lote 0G-17. La última caja sale de la fábrica, pero alguien ya la ha comprado.'},
 {name:'CEPILLO · PROTOCOLO FINAL',short:'CEPILLO FINAL',color:'#b8f6e5',warning:'¡SALTA EL BARRIDO!',intro:'QA-RL: «Nueva prioridad: ningún amigo debe acabar masticado».',open:'¡Se ha quedado sin batería! Golpea el núcleo.',outro:'QA-RL: «Ya no eres un producto». Gum: «¿Y este empleado qué hace aquí?».',lore:'La nueva etiqueta dice NO MASTICAR: PERSONA. Dr. Chew da por terminado el experimento. Gum decide que aún quiere seguir corriendo.'}
];
