function terrainSegment(a,b){if(b-a<1)return;const p=level.palette,step=16,bottom=Math.max(1250,camY+worldH+80),pts=[];pts.push({x:a,y:groundAt(level,a).y});for(let x=Math.ceil(a/step)*step;x<b;x+=step)if(x>a)pts.push({x,y:groundAt(level,x).y});pts.push({x:b,y:groundAt(level,b).y});
 ctx.beginPath();ctx.moveTo(a,bottom);pts.forEach(o=>ctx.lineTo(o.x,o.y));ctx.lineTo(b,bottom);ctx.closePath();const grad=ctx.createLinearGradient(0,430,0,1070);grad.addColorStop(0,p.ground);grad.addColorStop(1,p.sky);ctx.fillStyle=grad;ctx.fill();
 ctx.save();ctx.clip();ctx.fillStyle='#ffffff03';for(let x=Math.floor(a/120)*120;x<b;x+=120){ctx.fillStyle='#ffffff04';ctx.fillRect(x,380,59,1100);ctx.fillStyle='#ffffff0a';ctx.fillRect(x,380,2,1100)}
 ctx.strokeStyle=p.edge2+'45';ctx.lineWidth=3;for(let y=800;y<bottom;y+=220){ctx.beginPath();ctx.moveTo(a,y);ctx.lineTo(b,y);ctx.stroke();for(let x=Math.floor(a/200)*200;x<b;x+=200){ctx.fillStyle=p.edge2+'35';ctx.beginPath();ctx.arc(x+100,y+48,5,0,TAU);ctx.fill()}}
 ctx.restore();pathLine(pts);ctx.lineJoin='round';ctx.strokeStyle=p.sky;ctx.lineWidth=27;ctx.stroke();ctx.strokeStyle=p.edge2;ctx.lineWidth=19;ctx.stroke();ctx.strokeStyle=p.edge;ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='#fff4db99';ctx.lineWidth=2;ctx.stroke();
}
function drawGround(){const left=Math.max(-100,camX-90),right=Math.min(level.length+300,camX+worldW+140);let x=left;for(const g of level.gaps){if(g[1]<=left||g[0]>=right)continue;terrainSegment(x,Math.max(x,g[0]));x=Math.max(x,g[1])}terrainSegment(x,right);
 for(const g of level.gaps){if(g[1]<left||g[0]>right)continue;const y=Math.max(groundAt(level,g[0]).y,groundAt(level,g[1]).y)+187;ctx.fillStyle=level.palette.liquid+'b5';ctx.beginPath();ctx.moveTo(g[0],y+400);for(let xx=g[0];xx<=g[1]+3;xx+=8)ctx.lineTo(xx,y+Math.sin(xx*.038+visualT*3)*4);ctx.lineTo(g[1],y+400);ctx.closePath();ctx.fill();ctx.beginPath();for(let xx=g[0];xx<=g[1]+3;xx+=8){const yy=y+Math.sin(xx*.038+visualT*3)*4;if(xx===g[0])ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.strokeStyle=level.palette.liquid;ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#ffffff20';for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(g[0]+35+i*(g[1]-g[0]-60)/6,y+15+((visualT*20+i*19)%70),3+i%3,0,TAU);ctx.fill()}
 for(const xx of [g[0]-15,g[1]+15]){const yy=groundAt(level,xx).y;ctx.fillStyle='#2a2239';ctx.fillRect(xx-11,yy-27,22,30);ctx.fillStyle=level.palette.bright;ctx.fillRect(xx-12,yy-28,24,7);ctx.fillStyle=level.palette.liquid;ctx.beginPath();ctx.arc(xx,yy-42,5+Math.sin(visualT*4)*1,0,TAU);ctx.fill()}}
}
function visible(x,margin=180){return x>camX-margin&&x<camX+worldW+margin}
