/* @include "src/core/scope-open.js" */
/* @include "src/core/state.js" */
/* @include "src/game/campaign/worlds.js" */
/* @include "src/rendering/palettes.js" */
/* @include "src/game/data/materials-and-flavors.js" */
/* @include "src/game/data/humor-and-achievements.js" */
/* @include "src/game/campaign/generator.js" */
/* @include "src/game/physics/geometry.js" */
/* @include "src/core/reset.js" */
/* @include "src/game/campaign/session.js" */
/* @include "src/ui/base/overlay-and-menus.js" */
/* @include "src/game/campaign/lifecycle.js" */
/* @include "src/ui/base/results.js" */
/* @include "src/core/save.js" */
/* @include "src/ui/base/story-and-library.js" */
/* @include "src/ui/notifications/dialogue-and-awards.js" */
/* @include "src/game/mechanics/interactions.js" */
/* @include "src/ui/notifications/feedback.js" */
/* @include "src/audio/classic/legacy.js" */
/* @include "src/game/physics/movement.js" */
/* @include "src/game/update.js" */
/* @include "src/rendering/effects-update.js" */
/* @include "src/rendering/camera.js" */
/* @include "src/ui/hud.js" */
/* @include "src/core/events.js" */
/* @include "src/rendering/primitives.js" */
/* @include "src/rendering/background-classic.js" */
/* @include "src/rendering/terrain.js" */
/* @include "src/rendering/track-and-objects.js" */
/* @include "src/rendering/gum.js" */
/* @include "src/rendering/player.js" */
/* @include "src/rendering/feedback.js" */
/* @include "src/rendering/interactions.js" */
/* @include "src/rendering/collectibles-and-enemies.js" */
/* @include "src/rendering/npcs-and-props.js" */
/* @include "src/rendering/scene.js" */
/* @include "src/core/frame.js" */
/* @include "src/debug/core-hooks.js" */
/* @include "src/audio/classic/score.js" */
/* @include "src/audio/classic/synthesizer.js" */
/* @include "src/audio/classic/arrangement.js" */
/* @include "src/audio/classic/engine.js" */
/* @include "src/game/bosses/catalog.js" */
/* @include "src/game/bosses/arena.js" */
/* @include "src/game/bosses/combat.js" */
/* @include "src/game/bosses/integration.js" */
/* @include "src/game/bosses/practice.js" */
/* @include "src/rendering/background-painted.js" */
/* @include "src/rendering/bosses.js" */
/* @include "src/ui/base/bosses-and-jukebox.js" */
/* @include "src/debug/boss-hooks.js" */
/* @include "src/rendering/endless-assets.js" */
/* @include "src/game/endless/state.js" */
/* @include "src/game/endless/catalog.js" */
/* @include "src/game/endless/utilities.js" */
/* @include "src/game/endless/records.js" */
/* @include "src/ui/endless/lobby-and-records.js" */
/* @include "src/game/endless/session.js" */
/* @include "src/game/endless/generator.js" */
/* @include "src/game/endless/modules.js" */
/* @include "src/game/endless/arenas.js" */
/* @include "src/game/endless/biomes.js" */
/* @include "src/game/endless/recycling.js" */
/* @include "src/game/endless/lifecycle.js" */
/* @include "src/ui/endless/results-and-pause.js" */
/* @include "src/game/endless/integration.js" */
/* @include "src/rendering/endless-background.js" */
/* @include "src/rendering/endless-traps.js" */
/* @include "src/rendering/endless-integration.js" */
/* @include "src/audio/classic/endless-mix.js" */
/* @include "src/debug/endless-hooks.js" */
/* @include "src/game/endless/loop-reentry.js" */
/* @include "src/ui/index.js" */
/* @include "src/i18n/catalog.js" */
/* @include "src/audio/hd/assets.js" */
/* @include "src/i18n/localization.js" */
/* @include "src/audio/hd/state.js" */
/* @include "src/audio/director/state.js" */
/* @include "src/audio/ambient/state.js" */
/* @include "src/audio/hd/engine.js" */
/* @include "src/audio/director/events.js" */
/* @include "src/audio/director/danger.js" */
/* @include "src/audio/director/transitions.js" */
/* @include "src/audio/hd/scheduler.js" */
/* @include "src/audio/ambient/synthesizer.js" */
/* @include "src/audio/ambient/world-patterns.js" */
/* @include "src/audio/ambient/scheduler.js" */
/* @include "src/ui/audio/director-and-ambience.js" */
/* @include "src/audio/integration.js" */
/* @include "src/ui/audio/museum-and-options.js" */
/* @include "src/ui/title-controls.js" */
/* @include "src/debug/hd-hooks.js" */
/* @include "src/debug/music-director-hooks.js" */
/* @include "src/core/bootstrap.js" */
